not_simple = [
    'Доказать, что не может быть прото группа порядка $90$.',
    'Доказать, что не может быть прото группа порядка $120$.',
    'Доказать, что не может быть прото группа порядка $180$.',
    'Доказать, что не может быть прото группа порядка $240$.',
    'Доказать, что не может быть прото группа порядка $480$.',
    'Доказать, что не может быть прото группа порядка $336$.',
    'Доказать, что не может быть прото группа порядка $150$.',
    'Доказать, что не может быть прото группа порядка $420$.',
    'Доказать, что не может быть прото группа порядка $728$.',
    'Доказать, что не может быть прото группа порядка $264$.',
    'Доказать, что не может быть прото группа порядка $396$.',
]