shifts = [
    '''Рассматривается функция $f\colon\mathbb{R}\to\mathbb{R}$, заданная правилом:
    \[ f(x) = \begin{cases} 0 & \text{если $x<-1$ или $x>2$,} \\
    x+1 & \text{если $-1\leqslant x\leqslant 0$,} \\
    1 & \text{если $0<x<1$,} \\
    2-x & \text{если $1\leqslant x\leqslant2$.} \end{cases} \]
    Установите точные условия на набор вещественных чисел $a_1,\ldots,a_n\in\mathbb{R}$, для которых набор функций
    $f(x-a_1),\ldots,f(x-a_n)$ линейно независим в пространстве непрерывных функций на $\mathbb{R}$.''',

    '''Рассматривается функция $f\colon\mathbb{R}\to\mathbb{R}$, заданная правилом:
    \[ f(x) = \begin{cases} 0 & \text{если $x<-1$ или $x>1$,} \\
    x+1 & \text{если $-1\leqslant x< 0$,} \\
    1-x & \text{если $0\leqslant x\leqslant1$.} \end{cases} \]
    Установите точные условия на набор вещественных чисел $a_1,\ldots,a_n\in\mathbb{R}$, для которых набор функций
    $f(x-a_1),\ldots,f(x-a_n)$ линейно независим в пространстве непрерывных функций на $\mathbb{R}$.''',

    '''Рассматривается функция $f\colon\mathbb{R}\to\mathbb{R}$, вычисляющая по числу $x$ его целую часть.
    Установите точные условия на набор вещественных чисел $a_1,\ldots,a_n\in\mathbb{R}$, для которых набор функций
    $f(x-a_1),\ldots,f(x-a_n)$ линейно независим в пространстве функций на $\mathbb{R}$.''',

    '''Рассматривается функция $f\colon\mathbb{R}\to\mathbb{R}$, вычисляющая по числу $x$ его дробную часть.
    Установите точные условия на набор вещественных чисел $a_1,\ldots,a_n\in\mathbb{R}$, для которых набор функций
    $f(x-a_1),\ldots,f(x-a_n)$ линейно независим в пространстве функций на $\mathbb{R}$.''',

    '''Рассматривается функция $f\colon\mathbb{R}\to\mathbb{R}$,
    имеющая период $2$ и совпадающая на отрезке $[-1,1]$ с функцией $|x|$.
    Установите точные условия на набор вещественных чисел $a_1,\ldots,a_n\in\mathbb{R}$, для которых набор функций
    $f(x-a_1),\ldots,f(x-a_n)$ линейно независим в пространстве непрерывных функций на $\mathbb{R}$.''',
]